### ISSUE TITLE
The document coming soon

### ISSUE THREAD

**Issue by NatureLan-sudo** [bramtoula/multi_robot_SLAM_separators#3]
the document coming soon
Will the document still come?
@bramtoula

**Comment by bramtoula** [comment]
Hello, and thank you for your interest in this repository!

I am sorry for not updating the README earlier.

This project is meant to be used as part of [DOOR-SLAM](https://arxiv.org/abs/1909.12198).
The main DOOR-SLAM repository can be found [here](https://github.com/MISTLab/DOOR-SLAM), with documentation for using the full system [here](https://mistlab.ca/DOOR-SLAM/).

I have now updated the README to include this information.
